# Force Neovim as default editor system-wide
EDITOR=nvim
VISUAL=nvim

# Force Proton/VKD3D to expose NVIDIA features
PROTON_HIDE_NVIDIA_GPU=0
PROTON_ENABLE_NVAPI=1

# Disable DXR Raytracing translation & bypass upload hacks for Pascal GPUs
VKD3D_CONFIG=dxr0,no_upload_hacks
